// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9KanWfqR80LdF7BXeEJC83SwRgkFdafc',
    appId: '1:251753106054:web:a9086e9c837598cb545f07',
    messagingSenderId: '251753106054',
    projectId: 'flutter-final-hackathon-766f1',
    authDomain: 'flutter-final-hackathon-766f1.firebaseapp.com',
    storageBucket: 'flutter-final-hackathon-766f1.appspot.com',
    measurementId: 'G-WS3ZMF3T59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_z43xUsNfocQdp_NF_O_9bh-mV4iruyI',
    appId: '1:251753106054:android:e6fc7699c9074242545f07',
    messagingSenderId: '251753106054',
    projectId: 'flutter-final-hackathon-766f1',
    storageBucket: 'flutter-final-hackathon-766f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdks17HaEST_hFKOy46lDC7AfwIZ7dRLA',
    appId: '1:251753106054:ios:03e9c0dab409d1c5545f07',
    messagingSenderId: '251753106054',
    projectId: 'flutter-final-hackathon-766f1',
    storageBucket: 'flutter-final-hackathon-766f1.appspot.com',
    iosBundleId: 'com.example.finalhackathonapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdks17HaEST_hFKOy46lDC7AfwIZ7dRLA',
    appId: '1:251753106054:ios:03e9c0dab409d1c5545f07',
    messagingSenderId: '251753106054',
    projectId: 'flutter-final-hackathon-766f1',
    storageBucket: 'flutter-final-hackathon-766f1.appspot.com',
    iosBundleId: 'com.example.finalhackathonapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9KanWfqR80LdF7BXeEJC83SwRgkFdafc',
    appId: '1:251753106054:web:77a03f86db207f67545f07',
    messagingSenderId: '251753106054',
    projectId: 'flutter-final-hackathon-766f1',
    authDomain: 'flutter-final-hackathon-766f1.firebaseapp.com',
    storageBucket: 'flutter-final-hackathon-766f1.appspot.com',
    measurementId: 'G-2WW4Q25KRE',
  );
}
